### PR TITLE
Fix long message usage

### LINKED ISSUE #213: Fix long message usage

### PR DESCRIPTION
**Pull request by wujiaweijoanna**
Fixes #213 

屏幕截图(121)
屏幕截图(122)
屏幕截图(123)
屏幕截图(125)

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -23,19 +23,18 @@ public class AddCommand extends Command {
...
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a person to the address book.\n"
             + "Parameters: "
-            + PREFIX_NAME + "NAME "
-            + PREFIX_EMAIL + "EMAIL "
-            + PREFIX_GENDER + "GENDER "
-            + PREFIX_AGE + "AGE "
-            + "[" + PREFIX_DETAIL + "DETAIL] "
-            + "[" + PREFIX_STUDY_GROUP_TAG + "STUDY-GROUP-TAG]..."
-            + "\n"
+            + PREFIX_NAME + "NAME\n"
```
Comment (k-hian) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:26]: Should we standardise how the params are displayed? Currently, `Messages::format` adds a space at the start of a new line.

**Review by k-hian — COMMENTED** [review]
Just a small nit. Otherwise, LGTM.

File: src/main/java/seedu/address/logic/commands/AddCommand.java (hunk 1 above)
Comment (wujiaweijoanna) [reply src/main/java/seedu/address/logic/commands/AddCommand.java:26]: Thx for pointing it out, a space is now added before params.
